### ISSUE TITLE
fix typos and mixed indentation

### ISSUE THREAD

**Issue by sammy-ette** [Loggaby/Loggaby#1]
I have found that there are at least 2 typos in the readme and there is also some mixed indentation (tabs and spaces) in the library source. These should be fixed with the next version.

**Comment by sammy-ette** [comment]
ESLint should be ran as well to look for other issues

**Comment by RitikaGupta8734** [comment]
I think it would be better to replace unneeded with unwanted

**Comment by sammy-ette** [comment]
@RitikaGupta8734 good catch, but I also think completely changing that description is also a good idea.
and the short description can just have "an opinionated logger ..." etc
